# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chart
  pod 'Charts'
  pod 'TinyConstraints'

end
